console.log("Ikhwanda Pratama")
console.log(21)
console.log("Jln Wijaya Kusuma Pasar D1 ketahun")
console.log("Basket dan Ngegame")
console.log("SMK Negeri 05 Ketahun Bengkulu Utara")
console.log("Karena Saya sangat Tertarik Dunia Programmer Terutama Web developer")
console.log("Saya sudah mempelajari basic seperti HTML,CSS,JS dan Git and Github")
console.log("Sangat Pernah saya sangat kesulitan belajar JavaScript ")
console.log("Alasan nya karena saya ingin meningkatkan skill jadi Fullstack Web Developer")
console.log("Karena Saya cukup pandai menjalani di bidang Programmer ini sehingga saya tidak perlu belajar dari nol ")